/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.yangzc.gradle.plugin

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

/**
 * A simple functional test for the 'com.yangzc.gradle.plugin.greeting' plugin.
 */
class MybatisGenPluginFunctionalTest extends Specification {
    def "can run task"() {
        given:
        def projectDir = new File("build/functionalTest")
        projectDir.mkdirs()

        new File(projectDir, "settings.gradle").delete()
        new File(projectDir, "build.gradle").delete()

        new File(projectDir, "settings.gradle") << ""
        new File(projectDir, "build.gradle") << """
            plugins {
                id('com.codegen.gradle.plugin')
            }
        """

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("mybatisGenHelp")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.contains("This is mybatis generate plugin, list tasks")
    }
}
